<?php

declare(strict_types=1);

namespace Mondu\MonduPayment;

use Mondu\MonduPayment\Bootstrap\PaymentMethods;
use Shopware\Core\Framework\DataAbstractionLayer\Search\Criteria;
use Shopware\Core\Framework\DataAbstractionLayer\Search\Filter\EqualsFilter;
use Shopware\Core\Framework\Plugin;
use Shopware\Core\Framework\Plugin\Context\InstallContext;
use Shopware\Core\Framework\Plugin\Context\UpdateContext;

class MonduPayment extends Plugin {
    public function install(InstallContext $installContext): void
    {
        $bootstrapper = $this->getBootstrapClasses($installContext);

        foreach ($bootstrapper as $bootstrap) {
            $bootstrap->preInstall();
        }
        foreach ($bootstrapper as $bootstrap) {
            $bootstrap->install();
        }
        foreach ($bootstrapper as $bootstrap) {
            $bootstrap->postInstall();
        }

        parent::install($installContext); // TODO: Change the autogenerated stub
    }

    public function update(UpdateContext $updateContext): void
    {
        parent::update($updateContext); // TODO: Change the autogenerated stub
    }

    protected function getBootstrapClasses(InstallContext $installContext) {
        $bootstrapper = [
            new PaymentMethods()
        ];

        $pluginRepository = $this->container->get('plugin.repository');
        $plugins = $pluginRepository->search(
            (new Criteria())->addFilter(new EqualsFilter('baseClass', get_class($this))),
            $installContext->getContext()
        );

        $plugin = $plugins->first();

        foreach ($bootstrapper as $bootstrap) {
            $bootstrap->setInstallContext($installContext);
            //$bootstrap->setLogger($logger);
            $bootstrap->setContainer($this->container);
            $bootstrap->injectServices();
            $bootstrap->setPlugin($plugin);
        }

        return $bootstrapper;
    }
}
