jobs:
  # STAGE
  build_stage:
    on: push
    name: Build and push image to stage
    runs-on: [self-hosted, shared]
    timeout-minutes: 20
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3
      - uses: mondu-ai/cicd/auth-aws@v1
        with:
          aws_account_id: ${{ vars.STAGE_AWS_ACCOUNT_ID }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_profile_id: CICD
      - uses: mondu-ai/cicd/build-image@v1
        with:
          aws_account_id: ${{ vars.STAGE_AWS_ACCOUNT_ID }}
          repo: bnpl-plugins
          dockerfile: Dockerfile.stage
