name: Deploy
run-name: "Deploy from ${{ github.ref_name }}"

on:
  push:
    branches: [ main, remote-environment-1 ]
jobs:
  # STAGE
  build_stage:
    name: Build and push image to stage
    runs-on: ubuntu-latest
    timeout-minutes: 20
    if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/remote-environment-1' }}
    steps:
      - uses: actions/checkout@v3
      - uses: mondu-ai/cicd/auth-aws@v1
        with:
          aws_account_id: ${{ vars.STAGE_AWS_ACCOUNT_ID }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_profile_id: CICD
      - uses: mondu-ai/cicd/build-image@v1
        with:
          aws_account_id: ${{ vars.STAGE_AWS_ACCOUNT_ID }}
          repo: bnpl-plugins
          dockerfile: Dockerfile.stage
